---
# tasks file for deployment
- name: Deployment on kubernetes cluster
  shell: kubectl create -f demo.yaml
  #tags: deploy

  #- name: Deployment remove from  kubernetes cluster
  #shell: kubectl delete -f demo.yaml
  #tags: delete_deploy
